### ISSUE TITLE
老哥 maven install 报了这个错误

### ISSUE THREAD

**Issue by RAOE** [dragon-yuan/commutils4j#5]
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/Administrator/commutils4j/src/main/java/com/git/comm/utils/u4string/StringUtils.java:[4,26] 程序包com.sun.deploy.net不存在

**Comment by dragon-yuan** [comment]
小哥哥拉下master最新代码试试看，之前已经把sun包替换成java.net.URLEncoder了

**Comment by RAOE** [comment]
好的，解決了

**Comment by dragon-yuan** [comment]
好的！感谢兄弟。
